version: '2'

services:

 zf:
        build: .

        ports:
          - "8080:80"
          - "443:443"
        restart: always
        depends_on:
          - db
        volumes:
          - .:/var/www



 db:
      image: mysql/mysql-server:5.7
      ports:
         - "3306:3306"
      restart: always
      volumes:
        - testdb:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d

      environment:
              MYSQL_DATABASE: "chatbot"
              MYSQL_USER: "lucas"
              MYSQL_PASSWORD: "indi"
              MYSQL_ROOT_PASSWORD: "indi"
              
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   depends_on:
     - db
   restart: always
   ports:
     - "8081:80"
   environment:
     - MYSQL_USERNAME="lucas"
     - MYSQL_ROOT_PASSWORD="indi"
     - PMA_ARBITRARY=1

volumes:
   testdb: